# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/oppy/Repositories/interruptEvaluation/Project/vivado/z7_int_test_v1_plat/z7_int_test_v1_plat.srcs/sources_1/bd/design_int_test_z7_v1/ui/bd_8b366b01.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


