# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/int_design/int_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==int_design || ORIG_REF_NAME==int_design} -quiet] -quiet

# IP: bd/int_design/ip/int_design_zynq_ultra_ps_e_0_0/int_design_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==int_design_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==int_design_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/int_design/ip/int_design_xlconcat_0_0/int_design_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==int_design_xlconcat_0_0 || ORIG_REF_NAME==int_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/int_design/ip/int_design_xlslice_0_0/int_design_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==int_design_xlslice_0_0 || ORIG_REF_NAME==int_design_xlslice_0_0} -quiet] -quiet

# XDC: /home/oppy/Repositories/interruptEvaluation/Project/vivado/int_test_platform_v4/int_test_platform_v4.gen/sources_1/bd/int_design/int_design_ooc.xdc
