# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/oppy/Repositories/interruptEvaluation/Project/vivado/int_test_plat_v4/int_test_plat_v4.srcs/sources_1/bd/int_design/ip/int_design_zynq_ultra_ps_e_0_0/int_design_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'int_design_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oppy/Repositories/interruptEvaluation/Project/vivado/int_test_plat_v4/int_test_plat_v4.gen/sources_1/bd/int_design/ip/int_design_zynq_ultra_ps_e_0_0/int_design_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'int_design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/oppy/Repositories/interruptEvaluation/Project/vivado/int_test_plat_v4/int_test_plat_v4.gen/sources_1/bd/int_design/ip/int_design_zynq_ultra_ps_e_0_0/int_design_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'int_design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/oppy/Repositories/interruptEvaluation/Project/vivado/int_test_plat_v4/int_test_plat_v4.srcs/sources_1/bd/int_design/ip/int_design_zynq_ultra_ps_e_0_0/int_design_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'int_design_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oppy/Repositories/interruptEvaluation/Project/vivado/int_test_plat_v4/int_test_plat_v4.gen/sources_1/bd/int_design/ip/int_design_zynq_ultra_ps_e_0_0/int_design_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'int_design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/oppy/Repositories/interruptEvaluation/Project/vivado/int_test_plat_v4/int_test_plat_v4.gen/sources_1/bd/int_design/ip/int_design_zynq_ultra_ps_e_0_0/int_design_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'int_design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
