# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/zcu106_int_meas_plat/zcu106_int_meas_plat.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu106_int_meas_plat || ORIG_REF_NAME==zcu106_int_meas_plat} -quiet] -quiet

# IP: bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_zynq_ultra_ps_e_0_0/zcu106_int_meas_plat_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu106_int_meas_plat_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==zcu106_int_meas_plat_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: /home/oppy/vivado_workspace/zcu106_plat_int_measurement_v2/zcu106_plat_int_measurement.gen/sources_1/bd/zcu106_int_meas_plat/zcu106_int_meas_plat_ooc.xdc
