# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/zcu106_int_meas_plat/zcu106_int_meas_plat.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu106_int_meas_plat || ORIG_REF_NAME==zcu106_int_meas_plat} -quiet] -quiet

# IP: bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_rst_ps8_0_99M_0/zcu106_int_meas_plat_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu106_int_meas_plat_rst_ps8_0_99M_0 || ORIG_REF_NAME==zcu106_int_meas_plat_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_axi_gpio_0_0/zcu106_int_meas_plat_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu106_int_meas_plat_axi_gpio_0_0 || ORIG_REF_NAME==zcu106_int_meas_plat_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_axi_gpio_0_1/zcu106_int_meas_plat_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu106_int_meas_plat_axi_gpio_0_1 || ORIG_REF_NAME==zcu106_int_meas_plat_axi_gpio_0_1} -quiet] -quiet

# IP: bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_xbar_0/zcu106_int_meas_plat_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu106_int_meas_plat_xbar_0 || ORIG_REF_NAME==zcu106_int_meas_plat_xbar_0} -quiet] -quiet

# IP: bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_auto_ds_0/zcu106_int_meas_plat_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu106_int_meas_plat_auto_ds_0 || ORIG_REF_NAME==zcu106_int_meas_plat_auto_ds_0} -quiet] -quiet

# IP: bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_auto_pc_0/zcu106_int_meas_plat_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu106_int_meas_plat_auto_pc_0 || ORIG_REF_NAME==zcu106_int_meas_plat_auto_pc_0} -quiet] -quiet

# IP: bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_auto_ds_1/zcu106_int_meas_plat_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu106_int_meas_plat_auto_ds_1 || ORIG_REF_NAME==zcu106_int_meas_plat_auto_ds_1} -quiet] -quiet

# IP: bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_auto_pc_1/zcu106_int_meas_plat_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu106_int_meas_plat_auto_pc_1 || ORIG_REF_NAME==zcu106_int_meas_plat_auto_pc_1} -quiet] -quiet

# IP: bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_ps8_0_axi_periph_0/zcu106_int_meas_plat_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu106_int_meas_plat_ps8_0_axi_periph_0 || ORIG_REF_NAME==zcu106_int_meas_plat_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_zynq_ultra_ps_e_0_0/zcu106_int_meas_plat_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu106_int_meas_plat_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==zcu106_int_meas_plat_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: /home/oppy/vivado_workspace/zcu106_plat_int_measurement/zcu106_plat_int_measurement.gen/sources_1/bd/zcu106_int_meas_plat/zcu106_int_meas_plat_ooc.xdc
