# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/oppy/vivado_workspace/zcu106_plat_int_measurement/zcu106_plat_int_measurement.srcs/sources_1/bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_axi_gpio_0_0/zcu106_int_meas_plat_axi_gpio_0_0.xci
# IP: The module: 'zcu106_int_meas_plat_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oppy/vivado_workspace/zcu106_plat_int_measurement/zcu106_plat_int_measurement.gen/sources_1/bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_axi_gpio_0_0/zcu106_int_meas_plat_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_int_meas_plat_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/oppy/vivado_workspace/zcu106_plat_int_measurement/zcu106_plat_int_measurement.gen/sources_1/bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_axi_gpio_0_0/zcu106_int_meas_plat_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_int_meas_plat_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/oppy/vivado_workspace/zcu106_plat_int_measurement/zcu106_plat_int_measurement.gen/sources_1/bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_axi_gpio_0_0/zcu106_int_meas_plat_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_int_meas_plat_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/oppy/vivado_workspace/zcu106_plat_int_measurement/zcu106_plat_int_measurement.srcs/sources_1/bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_axi_gpio_0_0/zcu106_int_meas_plat_axi_gpio_0_0.xci
# IP: The module: 'zcu106_int_meas_plat_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oppy/vivado_workspace/zcu106_plat_int_measurement/zcu106_plat_int_measurement.gen/sources_1/bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_axi_gpio_0_0/zcu106_int_meas_plat_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_int_meas_plat_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/oppy/vivado_workspace/zcu106_plat_int_measurement/zcu106_plat_int_measurement.gen/sources_1/bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_axi_gpio_0_0/zcu106_int_meas_plat_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_int_meas_plat_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/oppy/vivado_workspace/zcu106_plat_int_measurement/zcu106_plat_int_measurement.gen/sources_1/bd/zcu106_int_meas_plat/ip/zcu106_int_meas_plat_axi_gpio_0_0/zcu106_int_meas_plat_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu106_int_meas_plat_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
