# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/zcu102_design_int/zcu102_design_int.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu102_design_int || ORIG_REF_NAME==zcu102_design_int} -quiet] -quiet

# IP: bd/zcu102_design_int/ip/zcu102_design_int_zynq_ultra_ps_e_0_0/zcu102_design_int_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu102_design_int_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==zcu102_design_int_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/zcu102_design_int/ip/zcu102_design_int_xlslice_0_0/zcu102_design_int_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu102_design_int_xlslice_0_0 || ORIG_REF_NAME==zcu102_design_int_xlslice_0_0} -quiet] -quiet

# IP: bd/zcu102_design_int/ip/zcu102_design_int_xlconcat_0_0/zcu102_design_int_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zcu102_design_int_xlconcat_0_0 || ORIG_REF_NAME==zcu102_design_int_xlconcat_0_0} -quiet] -quiet

# XDC: /home/oppy/Repositories/interruptEvaluation/Project/vivado/zcu102_int_plat_v5/zcu102_int_plat_v5.gen/sources_1/bd/zcu102_design_int/zcu102_design_int_ooc.xdc
