
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_INTERR_SOURCE_GPIO_DEVICE_ID,
		XPAR_INTERR_SOURCE_GPIO_BASEADDR,
		XPAR_INTERR_SOURCE_GPIO_INTERRUPT_PRESENT,
		XPAR_INTERR_SOURCE_GPIO_IS_DUAL
	},
	{
		XPAR_OUTPUT_EXTERNAL_GPIO_DEVICE_ID,
		XPAR_OUTPUT_EXTERNAL_GPIO_BASEADDR,
		XPAR_OUTPUT_EXTERNAL_GPIO_INTERRUPT_PRESENT,
		XPAR_OUTPUT_EXTERNAL_GPIO_IS_DUAL
	}
};


