# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/design_int_test_z7_v1/design_int_test_z7_v1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_test_z7_v1 || ORIG_REF_NAME==design_int_test_z7_v1} -quiet] -quiet

# IP: bd/design_int_test_z7_v1/ip/design_int_test_z7_v1_processing_system7_0_0/design_int_test_z7_v1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_test_z7_v1_processing_system7_0_0 || ORIG_REF_NAME==design_int_test_z7_v1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_int_test_z7_v1/ip/design_int_test_z7_v1_trace_clock_divider_0_0/design_int_test_z7_v1_trace_clock_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_test_z7_v1_trace_clock_divider_0_0 || ORIG_REF_NAME==design_int_test_z7_v1_trace_clock_divider_0_0} -quiet] -quiet

# XDC: /home/oppy/Repositories/interruptEvaluation/Project/vivado/z7_int_test_v1_plat/z7_int_test_v1_plat.gen/sources_1/bd/design_int_test_z7_v1/design_int_test_z7_v1_ooc.xdc
