# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/oppy/Repositories/interruptEvaluation/Project/vivado/zcu102_int_plat_v5/zcu102_int_plat_v5.srcs/sources_1/bd/zcu102_design_int/ip/zcu102_design_int_zynq_ultra_ps_e_0_0/zcu102_design_int_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'zcu102_design_int_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oppy/Repositories/interruptEvaluation/Project/vivado/zcu102_int_plat_v5/zcu102_int_plat_v5.gen/sources_1/bd/zcu102_design_int/ip/zcu102_design_int_zynq_ultra_ps_e_0_0/zcu102_design_int_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_design_int_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/oppy/Repositories/interruptEvaluation/Project/vivado/zcu102_int_plat_v5/zcu102_int_plat_v5.gen/sources_1/bd/zcu102_design_int/ip/zcu102_design_int_zynq_ultra_ps_e_0_0/zcu102_design_int_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_design_int_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/oppy/Repositories/interruptEvaluation/Project/vivado/zcu102_int_plat_v5/zcu102_int_plat_v5.srcs/sources_1/bd/zcu102_design_int/ip/zcu102_design_int_zynq_ultra_ps_e_0_0/zcu102_design_int_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'zcu102_design_int_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oppy/Repositories/interruptEvaluation/Project/vivado/zcu102_int_plat_v5/zcu102_int_plat_v5.gen/sources_1/bd/zcu102_design_int/ip/zcu102_design_int_zynq_ultra_ps_e_0_0/zcu102_design_int_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_design_int_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/oppy/Repositories/interruptEvaluation/Project/vivado/zcu102_int_plat_v5/zcu102_int_plat_v5.gen/sources_1/bd/zcu102_design_int/ip/zcu102_design_int_zynq_ultra_ps_e_0_0/zcu102_design_int_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_design_int_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
